modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://www.patihox.com" #optional

[[mods]] #mandatory

modId="phs-greenironmod" #mandatory

version="1.0" #mandatory

displayName="PatiHox's Green Iron" #mandatory

updateJSONURL="http://www.patihox.com" #optional

displayURL="http://www.patihox.com" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional

credits="Thanks for this mod goes to Java, FML Team and TurtyWurty" #optional

authors="PatiHox" #optional

description='''I don't know how would a green iron mod look if someone else made it (but it must be pretty common)
But this is how it should look from my point of view.

Hope you'll enjoy it :D
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.phs-greenironmod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

# Here's another dependency
[[dependencies.phs-greenironmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
